# Use root/example as user/password credentials
version: '3.1'

services:
  mongo-test:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - pteams-test:/data/db
  mongo-dev:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpassword
    ports:
      - "27018:27017"
    volumes:
      - pteams-dev:/data/db

volumes:
  pteams-dev:
  pteams-test: