name: Test Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code.
        uses: actions/checkout@v4 # Defaults to repository to which this workflow is attached.
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: npm ci # clean install; installs dependencies used in package-lock.json
      - name: Run tests
        run: npm test
  e2e-test-playwright:
    needs: unit-test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code.
        uses: actions/checkout@v4
      - name: Instal NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build the NextJS project.
        run: npm run build
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30